trigger:
- master

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

- task: AzureFunctionApp@1 # Add this at the end of your file
  inputs:    
    appType: functionAppLinux # default is functionApp
#     appName: $(appName)
    package: $(System.ArtifactsDirectory)/**/*.zip
    azureSubscription: '$(Parameters.AzureSubscription)'
#     appType: '$(Parameters.AppType)'
    appName: '$(Parameters.AppName)'    
    #Uncomment the next lines to deploy to a deployment slot
    #Note that deployment slots is not supported for Linux Dynamic SKU
    #deployToSlotOrASE: true
    #resourceGroupName: '<Resource Group Name>'
    #slotName: '<Slot name>'
